# This is a configuration file for data processing in a machine learning project.
loading_path_data:
  data_cars: '/Users/colin/Library/CloudStorage/OneDrive-UniversitedeMontreal/On_Going_Studies/IVADO_Project/car_prices.csv'
  data_population: '/Users/colin/Library/CloudStorage/OneDrive-UniversitedeMontreal/On_Going_Studies/IVADO_Project/states_populations_yr2015.csv'

# Prepare minimum frequencies for the extract_relevant_variables function
frequencies:
  year: 1
  make: 10000
  body: 1
  color: 10000
  interior: 10000

ordered_masks: []

ordered_min_frequencies: {}

unordered_masks:
  year:
    "1980": "1999"
    "1981": "1999"
    "1982": "1999"
    "1983": "1999"
    "1984": "1999"
    "1985": "1999"
    "1986": "1999"
    "1987": "1999"
    "1988": "1999"
    "1989": "1999"
    "1990": "1999"
    "1991": "1999"
    "1992": "1999"
    "1993": "1999"
    "1994": "1999"
    "1995": "1999"
    "1996": "1999"
    "1997": "1999"
    "1998": "1999"
    "1999": "1999"
  make:
    gmc truck: gmc
    dodge tk: dodge
    mazda tk: mazda
    hyundai tk: hyundai
    mercedes-b: mercedes-benz
    chev truck: chevrolet
    ford tk: ford
    ford truck: ford
    vw: volkswagen
  body: 
    # suvs1
    suv: suv      
    # sedans
    sedan: sedan
    g sedan: sedan
    elantra coupe: sedan
    # coupes
    coupe: coupe
    g coupe: coupe
    genesis coupe: coupe
    cts coupe: coupe
    koup: coupe
    cts-v coupe: coupe
    g37 coupe: coupe
    q60 coupe: coupe
    # convertibles
    convertible: convertible
    g convertible: convertible
    g37 convertible: convertible
    q60 convertible: convertible
    beetle convertible: convertible
    granturismo convertible: convertible
    # wagons
    wagon: wagon
    cts wagon: wagon
    tsx sport wagon: wagon
    cts-v wagon: wagon
    # hatchbacks
    hatchback: hatchback
    # vans / minivans
    minivan: van
    van: van
    e-series van: van
    promaster cargo van: van
    ram van: van
    transit van: van
    # pickup trucks - cab variants
    crew cab: pickup
    double cab: pickup
    crewmax cab: pickup
    access cab: pickup
    king cab: pickup
    supercrew: pickup
    extended cab: pickup
    supercab: pickup
    regular cab: pickup
    regular-cab: pickup
    quad cab: pickup
    club cab: pickup
    xtracab: pickup
    mega cab: pickup
    cab plus: pickup
    cab plus 4: pickup
  color: color_mask
  interior: interior_mask

unordered_min_frequencies:
  year: 1
  make: 10000
  body: 1
  color: 10000
  interior: 10000

var_of_interest:
  #marketid: 
  #  - 'marketid' 
  #market:
  #  - 'market'  
  marketvar:
    - 'sellingyear'
    - 'sellingmonth'
    - 'state'
  productvar: 'make'
  numerical:
    - 'sellingprice'
    - 'odometer'
    - 'condition'
    - 'mmr'
  ordered: []
  unordered:
    - 'year'
    - 'make'
    - 'body'
    - 'color'
    - 'interior'
  endog:
    - 'sellingprice'
  exog:
    - 'odometer'
    - 'condition'
    - 'year'
    - 'make'
    - 'body'
    - 'color'
    - 'interior'
  categorical:
    - 'state'
    - 'year'
    - 'make'
    - 'body'
    - 'color'
    - 'interior'
  
minisize_of_market : 20

instrument_creation:
  twodegree_polynomial_instruments: True
